// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AdjustMemberPointsData,
  AdjustMemberPointsResponses,
  CreateMemberMemoData,
  CreateMemberMemoResponses,
  DeleteMemberMemoData,
  DeleteMemberMemoResponses,
  ExportMembersData,
  ExportMembersResponses,
  GetMemberAuditLogsData,
  GetMemberAuditLogsResponses,
  GetMemberBasicInfoData,
  GetMemberBasicInfoResponses,
  GetMemberByIdData,
  GetMemberByIdResponses,
  GetMemberChangeHistoryData,
  GetMemberChangeHistoryResponses,
  GetMemberCommunicationsData,
  GetMemberCommunicationsResponses,
  GetMemberContractsData,
  GetMemberContractsResponses,
  GetMemberPointsData,
  GetMemberPointsResponses,
  GetMemberRelationshipsData,
  GetMemberRelationshipsResponses,
  GetMemberServiceUsageData,
  GetMemberServiceUsageResponses,
  GetMemberTrainingRecordsData,
  GetMemberTrainingRecordsResponses,
  GetMemberUsageHistoryData,
  GetMemberUsageHistoryResponses,
  GetMembersData,
  GetMembersResponses,
  SearchMembersData,
  SearchMembersResponses,
  UpdateMemberBasicInfoData,
  UpdateMemberBasicInfoResponses,
  UpdateMemberHealthInfoData,
  UpdateMemberHealthInfoResponses,
  UpdateMemberMarketingConsentData,
  UpdateMemberMarketingConsentResponses,
  UpdateMemberMemoData,
  UpdateMemberMemoResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Members {
  /**
   * Get members list (pagination, filtering, sorting)
   */
  public static getMembers<ThrowOnError extends boolean = false>(
    options?: Options<GetMembersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetMembersResponses, unknown, ThrowOnError>({
      url: '/members',
      ...options,
    });
  }

  /**
   * Member search (for quick search using keyword or QR scanning)
   */
  public static searchMembers<ThrowOnError extends boolean = false>(
    options: Options<SearchMembersData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<SearchMembersResponses, unknown, ThrowOnError>({
      url: '/members/search',
      ...options,
    });
  }

  /**
   * Execute export
   */
  public static exportMembers<ThrowOnError extends boolean = false>(
    options: Options<ExportMembersData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<ExportMembersResponses, unknown, ThrowOnError>({
      url: '/members/export',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class MemberDetails {
  /**
   * Get member details (Header common info)
   */
  public static getMemberById<ThrowOnError extends boolean = false>(
    options: Options<GetMemberByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberByIdResponses, unknown, ThrowOnError>({
      url: '/members/{id}',
      ...options,
    });
  }

  /**
   * Get Basic Info tab data
   */
  public static getMemberBasicInfo<ThrowOnError extends boolean = false>(
    options: Options<GetMemberBasicInfoData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberBasicInfoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/basic-info',
      ...options,
    });
  }

  /**
   * Update Basic Info
   */
  public static updateMemberBasicInfo<ThrowOnError extends boolean = false>(
    options: Options<UpdateMemberBasicInfoData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateMemberBasicInfoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/basic-info',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Update Health Info
   */
  public static updateMemberHealthInfo<ThrowOnError extends boolean = false>(
    options: Options<UpdateMemberHealthInfoData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateMemberHealthInfoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/health-info',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Update Marketing Consent
   */
  public static updateMemberMarketingConsent<ThrowOnError extends boolean = false>(
    options: Options<UpdateMemberMarketingConsentData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      UpdateMemberMarketingConsentResponses,
      unknown,
      ThrowOnError
    >({
      url: '/members/{id}/marketing-consent',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Get Contracts tab data
   */
  public static getMemberContracts<ThrowOnError extends boolean = false>(
    options: Options<GetMemberContractsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberContractsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/contracts',
      ...options,
    });
  }

  /**
   * Get Points tab data (by brand)
   */
  public static getMemberPoints<ThrowOnError extends boolean = false>(
    options: Options<GetMemberPointsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberPointsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/points',
      ...options,
    });
  }

  /**
   * Get Usage History tab data
   */
  public static getMemberUsageHistory<ThrowOnError extends boolean = false>(
    options: Options<GetMemberUsageHistoryData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberUsageHistoryResponses, unknown, ThrowOnError>({
      url: '/members/{id}/usage-history',
      ...options,
    });
  }

  /**
   * Get Training Records tab data
   */
  public static getMemberTrainingRecords<ThrowOnError extends boolean = false>(
    options: Options<GetMemberTrainingRecordsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberTrainingRecordsResponses, unknown, ThrowOnError>(
      { url: '/members/{id}/training-records', ...options },
    );
  }

  /**
   * Get Service Usage tab data
   */
  public static getMemberServiceUsage<ThrowOnError extends boolean = false>(
    options: Options<GetMemberServiceUsageData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberServiceUsageResponses, unknown, ThrowOnError>({
      url: '/members/{id}/service-usage',
      ...options,
    });
  }

  /**
   * Get Communications tab data
   */
  public static getMemberCommunications<ThrowOnError extends boolean = false>(
    options: Options<GetMemberCommunicationsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberCommunicationsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/communications',
      ...options,
    });
  }

  /**
   * Get Change History tab data
   */
  public static getMemberChangeHistory<ThrowOnError extends boolean = false>(
    options: Options<GetMemberChangeHistoryData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberChangeHistoryResponses, unknown, ThrowOnError>({
      url: '/members/{id}/change-history',
      ...options,
    });
  }

  /**
   * Get Relationships tab data
   */
  public static getMemberRelationships<ThrowOnError extends boolean = false>(
    options: Options<GetMemberRelationshipsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberRelationshipsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/relationships',
      ...options,
    });
  }

  /**
   * Get Audit Logs (Access logs, etc.)
   */
  public static getMemberAuditLogs<ThrowOnError extends boolean = false>(
    options: Options<GetMemberAuditLogsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<GetMemberAuditLogsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/audit-logs',
      ...options,
    });
  }
}

export class Points {
  /**
   * Adjust Points (Headquarter only)
   */
  public static adjustMemberPoints<ThrowOnError extends boolean = false>(
    options: Options<AdjustMemberPointsData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<AdjustMemberPointsResponses, unknown, ThrowOnError>({
      url: '/members/{id}/points/adjust',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Memos {
  /**
   * Add Memo
   */
  public static createMemberMemo<ThrowOnError extends boolean = false>(
    options: Options<CreateMemberMemoData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<CreateMemberMemoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/memos',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Delete Memo
   */
  public static deleteMemberMemo<ThrowOnError extends boolean = false>(
    options: Options<DeleteMemberMemoData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<DeleteMemberMemoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/memos/{memo_id}',
      ...options,
    });
  }

  /**
   * Update Memo
   */
  public static updateMemberMemo<ThrowOnError extends boolean = false>(
    options: Options<UpdateMemberMemoData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<UpdateMemberMemoResponses, unknown, ThrowOnError>({
      url: '/members/{id}/memos/{memo_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}
