// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type Token = {
    /**
     * Access Token
     */
    access_token?: string;
    /**
     * Refresh Token
     */
    refresh_token?: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Company Id
     */
    company_id?: number | null;
};

export type LoginResponse = {
    token?: Token;
};

export type RefreshTokenRequest = {
    /**
     * Refresh token to get new access token
     */
    refresh_token: string;
};

export type RefreshTokenResponse = {
    /**
     * New access token
     */
    accessToken?: string;
    /**
     * New refresh token
     */
    refresh_token?: string;
    /**
     * Token type (usually 'Bearer')
     */
    token_type?: string;
    /**
     * Company ID
     */
    company_id?: number | null;
};

export type GetMembersResponse = {
    members?: Array<MemberListItem>;
    pagination?: Pagination;
};

export type MemberListItem = {
    id?: string;
    member_number?: string;
    name_kanji?: string;
    name_kana?: string;
    member_type?: 'regular' | 'family' | 'corporate' | 'company_discount';
    status?: 'active' | 'suspended' | 'withdrawn' | 'force_withdrawn';
    store_name?: string;
    brand?: 'joyfit' | 'fit365';
    contract_plan_name?: string;
    joined_at?: string;
    last_visit_date?: string | null;
    has_unpaid?: boolean;
};

export type Pagination = {
    page?: number;
    limit?: number;
    total?: number;
    total_pages?: number;
};

export type GetMemberDetailResponse = {
    member?: {
        [key: string]: unknown;
    };
};

export type UpdateBasicInfoRequest = {
    name_kanji?: string;
    name_kana?: string;
    postal_code?: string;
    phone?: string;
    email?: string;
};

export type PointAdjustmentRequest = {
    type: 'add' | 'subtract';
    points: number;
    reason: string;
};

export type CreateMemoRequest = {
    type: 'caution' | 'vip' | 'other';
    content: string;
};

export type ExportMembersRequest = {
    format: 'csv' | 'excel';
    target: 'selected' | 'filtered';
    member_ids?: Array<string>;
    fields: Array<string>;
};

export type Error = {
    error?: string;
};

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized - Invalid or expired refresh token
     */
    401: Error;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: RefreshTokenResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetCrmMembersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
        /**
         * Search by member number, name, phone, or email
         */
        search?: string;
        /**
         * Filter by member type
         */
        member_type?: Array<'regular' | 'family' | 'corporate' | 'company_discount'>;
        /**
         * Filter by status
         */
        status?: Array<'active' | 'suspended' | 'withdrawn' | 'force_withdrawn'>;
        /**
         * Filter by brand
         */
        brand?: Array<'joyfit' | 'fit365'>;
        /**
         * Filter by store ID
         */
        store_id?: Array<string>;
        /**
         * Filter by contract plan ID
         */
        contract_plan_id?: Array<string>;
        /**
         * Filter by last visit days (7=1週間以内, 30=1ヶ月以内, 90=3ヶ月以内, -1=3ヶ月以上)
         */
        last_visit_days?: number;
        /**
         * Filter by unpaid status
         */
        has_unpaid?: boolean;
        /**
         * Sort field
         */
        sort_by?: 'member_number' | 'joined_at' | 'last_visit' | 'name';
        /**
         * Sort order
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/crm/members';
};

export type GetCrmMembersResponses = {
    /**
     * Success
     */
    200: GetMembersResponse;
};

export type GetCrmMembersResponse = GetCrmMembersResponses[keyof GetCrmMembersResponses];

export type GetCrmMembersByIdData = {
    body?: never;
    path: {
        /**
         * Member ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}';
};

export type GetCrmMembersByIdErrors = {
    /**
     * Member not found
     */
    404: Error;
};

export type GetCrmMembersByIdError = GetCrmMembersByIdErrors[keyof GetCrmMembersByIdErrors];

export type GetCrmMembersByIdResponses = {
    /**
     * Success
     */
    200: GetMemberDetailResponse;
};

export type GetCrmMembersByIdResponse = GetCrmMembersByIdResponses[keyof GetCrmMembersByIdResponses];

export type GetCrmMembersByIdBasicInfoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/basic-info';
};

export type GetCrmMembersByIdBasicInfoResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdBasicInfoResponse = GetCrmMembersByIdBasicInfoResponses[keyof GetCrmMembersByIdBasicInfoResponses];

export type PutCrmMembersByIdBasicInfoData = {
    body: UpdateBasicInfoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/basic-info';
};

export type PutCrmMembersByIdBasicInfoResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCrmMembersByIdContractsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/contracts';
};

export type GetCrmMembersByIdContractsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCrmMembersByIdPointsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points';
};

export type GetCrmMembersByIdPointsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCrmMembersByIdPointsData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points';
};

export type PostCrmMembersByIdPointsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembersByIdPointsError = PostCrmMembersByIdPointsErrors[keyof PostCrmMembersByIdPointsErrors];

export type PostCrmMembersByIdPointsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembersByIdPointsResponse = PostCrmMembersByIdPointsResponses[keyof PostCrmMembersByIdPointsResponses];

export type PostCrmMembersByIdPointsAdjustData = {
    body: PointAdjustmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points/adjust';
};

export type PostCrmMembersByIdPointsAdjustResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCrmMembersByIdMemosData = {
    body: CreateMemoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos';
};

export type PostCrmMembersByIdMemosResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostCrmMembersExportData = {
    body: ExportMembersRequest;
    path?: never;
    query?: never;
    url: '/crm/members/export';
};

export type PostCrmMembersExportResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetCrmMembersByIdChangeHistoryData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/change-history';
};

export type GetCrmMembersByIdChangeHistoryErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdChangeHistoryError = GetCrmMembersByIdChangeHistoryErrors[keyof GetCrmMembersByIdChangeHistoryErrors];

export type GetCrmMembersByIdChangeHistoryResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdChangeHistoryResponse = GetCrmMembersByIdChangeHistoryResponses[keyof GetCrmMembersByIdChangeHistoryResponses];

export type GetCrmMembersByIdCommunicationsData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/communications';
};

export type GetCrmMembersByIdCommunicationsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdCommunicationsError = GetCrmMembersByIdCommunicationsErrors[keyof GetCrmMembersByIdCommunicationsErrors];

export type GetCrmMembersByIdCommunicationsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdCommunicationsResponse = GetCrmMembersByIdCommunicationsResponses[keyof GetCrmMembersByIdCommunicationsResponses];

export type PutCrmMembersByIdHealthInfoData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/health-info';
};

export type PutCrmMembersByIdHealthInfoErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdHealthInfoError = PutCrmMembersByIdHealthInfoErrors[keyof PutCrmMembersByIdHealthInfoErrors];

export type PutCrmMembersByIdHealthInfoResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutCrmMembersByIdHealthInfoResponse = PutCrmMembersByIdHealthInfoResponses[keyof PutCrmMembersByIdHealthInfoResponses];

export type PutCrmMembersByIdMarketingConsentData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/marketing-consent';
};

export type PutCrmMembersByIdMarketingConsentErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdMarketingConsentError = PutCrmMembersByIdMarketingConsentErrors[keyof PutCrmMembersByIdMarketingConsentErrors];

export type PutCrmMembersByIdMarketingConsentResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutCrmMembersByIdMarketingConsentResponse = PutCrmMembersByIdMarketingConsentResponses[keyof PutCrmMembersByIdMarketingConsentResponses];

export type DeleteCrmMembersByIdMemosByMemoIdData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
        /**
         * memoId parameter
         */
        memoId: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos/{memoId}';
};

export type DeleteCrmMembersByIdMemosByMemoIdErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type DeleteCrmMembersByIdMemosByMemoIdError = DeleteCrmMembersByIdMemosByMemoIdErrors[keyof DeleteCrmMembersByIdMemosByMemoIdErrors];

export type DeleteCrmMembersByIdMemosByMemoIdResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteCrmMembersByIdMemosByMemoIdResponse = DeleteCrmMembersByIdMemosByMemoIdResponses[keyof DeleteCrmMembersByIdMemosByMemoIdResponses];

export type PutCrmMembersByIdMemosByMemoIdData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
        /**
         * memoId parameter
         */
        memoId: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos/{memoId}';
};

export type PutCrmMembersByIdMemosByMemoIdErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdMemosByMemoIdError = PutCrmMembersByIdMemosByMemoIdErrors[keyof PutCrmMembersByIdMemosByMemoIdErrors];

export type PutCrmMembersByIdMemosByMemoIdResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutCrmMembersByIdMemosByMemoIdResponse = PutCrmMembersByIdMemosByMemoIdResponses[keyof PutCrmMembersByIdMemosByMemoIdResponses];

export type GetCrmMembersByIdRelationshipsData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/relationships';
};

export type GetCrmMembersByIdRelationshipsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdRelationshipsError = GetCrmMembersByIdRelationshipsErrors[keyof GetCrmMembersByIdRelationshipsErrors];

export type GetCrmMembersByIdRelationshipsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdRelationshipsResponse = GetCrmMembersByIdRelationshipsResponses[keyof GetCrmMembersByIdRelationshipsResponses];

export type GetCrmMembersByIdServiceUsageData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/service-usage';
};

export type GetCrmMembersByIdServiceUsageErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdServiceUsageError = GetCrmMembersByIdServiceUsageErrors[keyof GetCrmMembersByIdServiceUsageErrors];

export type GetCrmMembersByIdServiceUsageResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdServiceUsageResponse = GetCrmMembersByIdServiceUsageResponses[keyof GetCrmMembersByIdServiceUsageResponses];

export type GetCrmMembersByIdTrainingRecordsData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/training-records';
};

export type GetCrmMembersByIdTrainingRecordsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdTrainingRecordsError = GetCrmMembersByIdTrainingRecordsErrors[keyof GetCrmMembersByIdTrainingRecordsErrors];

export type GetCrmMembersByIdTrainingRecordsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdTrainingRecordsResponse = GetCrmMembersByIdTrainingRecordsResponses[keyof GetCrmMembersByIdTrainingRecordsResponses];

export type GetCrmMembersByIdUsageHistoryData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/usage-history';
};

export type GetCrmMembersByIdUsageHistoryErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdUsageHistoryError = GetCrmMembersByIdUsageHistoryErrors[keyof GetCrmMembersByIdUsageHistoryErrors];

export type GetCrmMembersByIdUsageHistoryResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembersByIdUsageHistoryResponse = GetCrmMembersByIdUsageHistoryResponses[keyof GetCrmMembersByIdUsageHistoryResponses];

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetOpenapiJsonError = GetOpenapiJsonErrors[keyof GetOpenapiJsonErrors];

export type GetOpenapiJsonResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenapiJsonResponse = GetOpenapiJsonResponses[keyof GetOpenapiJsonResponses];

export type PostAuthRegisterData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];
