// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type Token = {
    /**
     * Access Token
     */
    access_token?: string;
    /**
     * Refresh Token
     */
    refresh_token?: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Company Id
     */
    company_id?: number | null;
};

export type LoginResponse = {
    token?: Token;
};

export type RefreshTokenRequest = {
    /**
     * Refresh token to get new access token
     */
    refresh_token: string;
};

export type RefreshTokenResponse = {
    /**
     * New access token
     */
    accessToken?: string;
    /**
     * New refresh token
     */
    refresh_token?: string;
    /**
     * Token type (usually 'Bearer')
     */
    token_type?: string;
    /**
     * Company ID
     */
    company_id?: number | null;
};

export type GetMembersResponse = {
    members?: Array<MemberListItem>;
    pagination?: Pagination;
};

export type MemberListItem = {
    id?: string;
    member_number?: string;
    name_kanji?: string;
    name_kana?: string;
    member_type?: 'regular' | 'family' | 'corporate' | 'company_discount';
    status?: 'active' | 'suspended' | 'withdrawn' | 'force_withdrawn';
    store_name?: string;
    brand?: 'joyfit' | 'fit365';
    contract_plan_name?: string;
    joined_at?: string;
    last_visit_date?: string | null;
    has_unpaid?: boolean;
};

export type Pagination = {
    page?: number;
    limit?: number;
    total?: number;
    total_pages?: number;
};

export type EmergencyContact = {
    /**
     * 緊急連絡先氏名
     */
    name: string;
    /**
     * 続柄
     */
    relationship: string;
    /**
     * 電話番号
     */
    phone: string;
};

export type MemberBasicInfo = {
    id: string;
    /**
     * 会員番号
     */
    member_number: string;
    /**
     * 氏名（漢字）
     */
    name_kanji: string;
    /**
     * 氏名（カナ）
     */
    name_kana: string;
    /**
     * 生年月日
     */
    birthday: string;
    /**
     * 年齢
     */
    age: number;
    /**
     * 性別
     */
    gender: 'male' | 'female' | 'other';
    /**
     * 郵便番号
     */
    postal_code?: string;
    /**
     * 都道府県
     */
    prefecture?: string;
    /**
     * 市区町村
     */
    city?: string;
    /**
     * 番地
     */
    address?: string;
    /**
     * 建物名
     */
    building?: string;
    /**
     * 電話番号
     */
    phone: string;
    /**
     * メールアドレス
     */
    email: string;
    emergency_contact?: EmergencyContact;
};

export type MemberProfile = {
    /**
     * 会員種別
     */
    member_type: 'regular' | 'family' | 'corporate' | 'company_discount';
    /**
     * 会員ステータス
     */
    status: 'active' | 'suspended' | 'withdrawn' | 'force_withdrawn';
    /**
     * 店舗ID
     */
    store_id: string;
    /**
     * 所属店舗
     */
    store_name: string;
    /**
     * 所属ブランド
     */
    brand: 'joyfit' | 'fit365';
    /**
     * 入会日
     */
    joined_at: string;
    /**
     * 退会日
     */
    withdrawn_at?: string | null;
    /**
     * ブラックリスト登録状況
     */
    is_black_listed: boolean;
};

export type MemberEkyc = {
    /**
     * eKYC検証結果
     */
    verified: boolean;
    /**
     * 検証日時
     */
    verified_at?: string;
    /**
     * 本人確認書類の種類
     */
    document_type?: string;
    /**
     * 顔写真URL
     */
    photoUrl?: string;
};

export type MemberConsent = {
    member_agreement: {
        version: string;
        agreed_at: string;
    };
    privacy_policy: {
        version: string;
        agreed_at: string;
    };
    optional_agreement?: {
        version?: string;
        agreed_at?: string;
    };
    marketing_consent: {
        email: boolean;
        sms: boolean;
        push: boolean;
    };
};

export type MemberHealthInfo = {
    /**
     * 健康状態申告
     */
    health_status?: string;
    /**
     * 既往歴・持病
     */
    medical_history?: string;
    /**
     * アレルギー情報
     */
    allergies?: string;
    /**
     * 運動制限事項
     */
    exercise_restrictions?: string;
    /**
     * その他特記事項
     */
    other_notes?: string;
};

export type Member = {
    basic_info: MemberBasicInfo;
    profile: MemberProfile;
    ekyc?: MemberEkyc;
    consent?: MemberConsent;
    health_info?: MemberHealthInfo;
};

export type GetMemberDetailResponse = {
    member: Member;
};

/**
 * GET /crm/members/{id}/basic-info レスポンス（基本情報タブ用）
 */
export type GetBasicInfoResponse = {
    member: Member;
};

/**
 * PUT /crm/members/{id}/basic-info レスポンス
 */
export type PutBasicInfoResponse = {
    success?: boolean;
    id?: string;
    /**
     * 更新されたフィールド
     */
    updated?: {
        [key: string]: unknown;
    };
};

/**
 * PUT /crm/members/{id}/basic-info リクエスト（個人情報の更新）
 */
export type UpdateBasicInfoRequest = {
    name_kanji?: string;
    name_kana?: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    address?: string;
    building?: string;
    phone?: string;
    email?: string;
    emergency_contact?: EmergencyContact;
};

/**
 * PUT /crm/members/{id}/health-info リクエスト
 */
export type UpdateHealthInfoRequest = {
    health_status?: string;
    medical_history?: string;
    allergies?: string;
    exercise_restrictions?: string;
    other_notes?: string;
};

export type PutHealthInfoResponse = {
    success?: boolean;
    health_info?: MemberHealthInfo;
};

/**
 * PUT /crm/members/{id}/marketing-consent リクエスト
 */
export type UpdateMarketingConsentRequest = {
    email?: boolean;
    sms?: boolean;
    push?: boolean;
};

export type PutMarketingConsentResponse = {
    success?: boolean;
};

export type PointAdjustmentResponse = {
    success?: boolean;
    new_balance?: number;
};

export type ContractChange = {
    changed_at?: string;
    previous_plan?: string;
    new_plan?: string;
    reason?: string;
};

export type MainContract = {
    /**
     * 現在の主契約プラン名
     */
    plan_name?: string;
    /**
     * 月会費（税込）
     */
    monthly_fee?: number;
    start_date?: string;
    /**
     * 違約金発生期間終了日
     */
    penalty_period_end?: string;
    change_history?: Array<ContractChange>;
};

export type OptionContract = {
    id?: string;
    /**
     * オプション名
     */
    name?: string;
    /**
     * 月額料金
     */
    monthly_fee?: number;
    start_date?: string;
    /**
     * 次回請求日
     */
    next_billing_date?: string;
};

export type OptionChangeHistoryItem = {
    changed_at?: string;
    option_name?: string;
    action_type?: 'add' | 'remove' | 'change';
    notes?: string;
};

export type SpecialContractItem = {
    enrolled?: boolean;
    start_date?: string;
    /**
     * 請求月
     */
    applied_month?: string;
};

export type SpecialContracts = {
    anshin_support?: SpecialContractItem;
    mutual_use?: SpecialContractItem;
    security_fee?: SpecialContractItem;
    maintenance_fee?: SpecialContractItem;
};

export type PaymentRecord = {
    date?: string;
    amount?: number;
    breakdown?: string;
    status?: 'success' | 'failed';
    notes?: string;
};

export type PaymentInfo = {
    method?: 'credit_card' | 'bank_transfer';
    /**
     * マスク済み、下4桁
     */
    card_number?: string;
    cardholder_name?: string;
    expiry_date?: string;
    billing_day?: number;
    last_payment_date?: string;
    last_payment_amount?: number;
    status?: 'normal' | 'error';
    payment_history?: Array<PaymentRecord>;
};

export type UnpaidItem = {
    month?: string;
    amount?: number;
    reason?: string;
    reminder_status?: string;
};

export type CampaignActiveItem = {
    campaign_name?: string;
    period_start?: string;
    period_end?: string;
    discount_content?: string;
    remaining_days?: number;
};

export type CampaignHistoryItem = {
    applied_at?: string;
    campaign_name?: string;
    content?: string;
    status?: 'active' | 'expired' | 'cancelled';
};

/**
 * 契約情報タブ用レスポンス
 */
export type GetContractsResponse = {
    main_contract?: MainContract;
    option_contracts?: Array<OptionContract>;
    option_change_history?: Array<OptionChangeHistoryItem>;
    special_contracts?: SpecialContracts;
    payment_info?: PaymentInfo;
    unpaid_info?: {
        items?: Array<UnpaidItem>;
    };
    campaigns?: {
        active?: Array<CampaignActiveItem>;
        history?: Array<CampaignHistoryItem>;
    };
};

/**
 * ブランド別ポイント保有（member_points に紐づく想定）。FIT365=ベアレージ、JOYFIT=エンジョイ
 */
export type BrandPointBalance = {
    /**
     * 現在の保有ポイント
     */
    current_balance?: number;
    /**
     * 累計獲得ポイント
     */
    total_earned?: number;
    /**
     * 累計消費ポイント
     */
    total_spent?: number;
    /**
     * 有効期限（none=無期限）
     */
    expiry?: string;
    /**
     * 利用先
     */
    usage_destination?: string;
};

/**
 * 会員ランク情報
 */
export type MemberRankInfo = {
    /**
     * 現在のランク（ブロンズ/シルバー/ゴールド/プラチナなど）
     */
    current?: string;
    /**
     * ランク特典内容
     */
    benefits?: string;
    next_rank?: {
        /**
         * 次回ランクアップ必要ポイント
         */
        required_points?: number;
        /**
         * 進捗率%
         */
        progress?: number;
    };
};

/**
 * ポイント獲得履歴（member_point_histories type=earn）
 */
export type PointEarnRecord = {
    id?: string;
    /**
     * 獲得日時
     */
    date?: string;
    /**
     * 獲得理由（来館/友達紹介/キャンペーン/誕生日ボーナスなど）
     */
    reason?: string;
    points?: number;
    /**
     * 詳細・備考
     */
    notes?: string;
};

/**
 * ポイント消費履歴（member_point_histories type=spend）
 */
export type PointSpendRecord = {
    id?: string;
    /**
     * 消費日時
     */
    date?: string;
    /**
     * 消費内容（月会費充当/EC決済/商品交換/ギフトカード交換など）
     */
    content?: string;
    points?: number;
    /**
     * 詳細・備考
     */
    notes?: string;
};

/**
 * ポイント調整履歴（member_point_histories type=adjust）
 */
export type PointAdjustmentRecord = {
    id?: string;
    /**
     * 調整日時
     */
    date?: string;
    /**
     * 手動付与/手動減算
     */
    adjustment_type?: 'add' | 'subtract';
    points?: number;
    /**
     * 調整理由
     */
    reason?: string;
    /**
     * 実施スタッフ
     */
    adjusted_by?: string;
};

/**
 * GET /crm/members/{id}/points レスポンス（ポイントタブ用）。member_points / member_point_histories に相当
 */
export type GetPointsResponse = {
    fit365?: BrandPointBalance;
    joyfit?: BrandPointBalance;
    rank?: MemberRankInfo;
    /**
     * ポイント獲得履歴（最近20件・全件表示可）
     */
    earn_history?: Array<PointEarnRecord>;
    /**
     * ポイント消費履歴（最近20件・全件表示可）
     */
    spend_history?: Array<PointSpendRecord>;
    /**
     * ポイント調整履歴（該当する場合）
     */
    adjustment_history?: Array<PointAdjustmentRecord>;
};

export type PostPointsAdjustResponse = {
    success?: boolean;
    new_balance?: number;
};

export type GetChangeHistoryResponse = {
    items?: Array<{
        id?: string;
        date?: string;
        event_type?: string;
        content?: string;
    }>;
};

export type GetRelationshipsResponse = {
    family?: {
        [key: string]: unknown;
    };
    corporate?: {
        [key: string]: unknown;
    };
    referral?: {
        [key: string]: unknown;
    };
};

export type GetServiceUsageResponse = {
    personal_training?: {
        [key: string]: unknown;
    };
    studio_programs?: {
        [key: string]: unknown;
    };
    other_services?: {
        [key: string]: unknown;
    };
};

export type GetTrainingRecordsResponse = {
    summary?: {
        [key: string]: unknown;
    };
    strength_records?: Array<unknown>;
    cardio_records?: Array<unknown>;
    body_records?: Array<unknown>;
};

export type GetUsageHistoryResponse = {
    summary?: {
        [key: string]: unknown;
    };
    visits?: Array<unknown>;
    store_usage?: Array<unknown>;
};

export type ExportMembersResponse = {
    success?: boolean;
    download_url?: string;
    expires_at?: string;
};

export type RegisterRequest = {
    email?: string;
    password?: string;
    name?: string;
};

export type RegisterResponse = {
    success?: boolean;
    user_id?: string;
};

export type PointAdjustmentRequest = {
    type: 'add' | 'subtract';
    points: number;
    reason: string;
};

export type CreateMemoRequest = {
    /**
     * メモ種別（要注意/VIP/その他）
     */
    type: 'caution' | 'vip' | 'other';
    /**
     * メモ内容（1000文字まで）
     */
    content: string;
    /**
     * 記録スタッフ（未指定時はAPIでデフォルト設定）
     */
    created_by?: string;
};

export type UpdateMemoRequest = {
    type?: 'caution' | 'vip' | 'other';
    content?: string;
};

export type StaffMemo = {
    /**
     * メモID
     */
    id: string;
    /**
     * 記録日時
     */
    date: string;
    /**
     * メモ種別
     */
    type: 'caution' | 'vip' | 'other';
    /**
     * メモ内容
     */
    content: string;
    /**
     * 記録スタッフ
     */
    created_by: string;
};

export type CreateMemoResponse = {
    success?: boolean;
    memo?: StaffMemo;
};

export type UpdateMemoResponse = {
    success?: boolean;
    memo?: StaffMemo;
};

export type ExportMembersRequest = {
    format: 'csv' | 'excel';
    target: 'selected' | 'filtered';
    member_ids?: Array<string>;
    fields: Array<string>;
};

/**
 * コミュニケーションタブ取得レスポンス
 */
export type GetCommunicationsResponse = {
    /**
     * スタッフメモ一覧
     */
    memos?: Array<StaffMemo>;
    inquiries?: Array<{
        id?: string;
        date?: string;
        content?: string;
        staff_name?: string;
        result?: string;
        status?: 'in_progress' | 'completed';
    }>;
    notifications?: {
        [key: string]: unknown;
    };
    phoneRecords?: Array<unknown>;
};

export type Error = {
    error?: string;
};

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized - Invalid or expired refresh token
     */
    401: Error;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: RefreshTokenResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetCrmMembersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
        /**
         * Search by member number, name, phone, or email
         */
        search?: string;
        /**
         * Filter by member type
         */
        member_type?: Array<'regular' | 'family' | 'corporate' | 'company_discount'>;
        /**
         * Filter by status
         */
        status?: Array<'active' | 'suspended' | 'withdrawn' | 'force_withdrawn'>;
        /**
         * Filter by brand
         */
        brand?: Array<'joyfit' | 'fit365'>;
        /**
         * Filter by store ID
         */
        store_id?: Array<string>;
        /**
         * Filter by contract plan ID
         */
        contract_plan_id?: Array<string>;
        /**
         * Filter by last visit days (7=1週間以内, 30=1ヶ月以内, 90=3ヶ月以内, -1=3ヶ月以上)
         */
        last_visit_days?: number;
        /**
         * Filter by unpaid status
         */
        has_unpaid?: boolean;
        /**
         * Sort field
         */
        sort_by?: 'member_number' | 'joined_at' | 'last_visit' | 'name';
        /**
         * Sort order
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/crm/members';
};

export type GetCrmMembersResponses = {
    /**
     * Success
     */
    200: GetMembersResponse;
};

export type GetCrmMembersResponse = GetCrmMembersResponses[keyof GetCrmMembersResponses];

export type GetCrmMembersByIdData = {
    body?: never;
    path: {
        /**
         * Member ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}';
};

export type GetCrmMembersByIdErrors = {
    /**
     * Member not found
     */
    404: Error;
};

export type GetCrmMembersByIdError = GetCrmMembersByIdErrors[keyof GetCrmMembersByIdErrors];

export type GetCrmMembersByIdResponses = {
    /**
     * Success
     */
    200: GetMemberDetailResponse;
};

export type GetCrmMembersByIdResponse = GetCrmMembersByIdResponses[keyof GetCrmMembersByIdResponses];

export type GetCrmMembersByIdBasicInfoData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/basic-info';
};

export type GetCrmMembersByIdBasicInfoErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdBasicInfoError = GetCrmMembersByIdBasicInfoErrors[keyof GetCrmMembersByIdBasicInfoErrors];

export type GetCrmMembersByIdBasicInfoResponses = {
    /**
     * Success
     */
    200: GetBasicInfoResponse;
};

export type GetCrmMembersByIdBasicInfoResponse = GetCrmMembersByIdBasicInfoResponses[keyof GetCrmMembersByIdBasicInfoResponses];

export type PutCrmMembersByIdBasicInfoData = {
    body: UpdateBasicInfoRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/basic-info';
};

export type PutCrmMembersByIdBasicInfoErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdBasicInfoError = PutCrmMembersByIdBasicInfoErrors[keyof PutCrmMembersByIdBasicInfoErrors];

export type PutCrmMembersByIdBasicInfoResponses = {
    /**
     * Success
     */
    200: PutBasicInfoResponse;
};

export type PutCrmMembersByIdBasicInfoResponse = PutCrmMembersByIdBasicInfoResponses[keyof PutCrmMembersByIdBasicInfoResponses];

export type GetCrmMembersByIdContractsData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/contracts';
};

export type GetCrmMembersByIdContractsErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdContractsError = GetCrmMembersByIdContractsErrors[keyof GetCrmMembersByIdContractsErrors];

export type GetCrmMembersByIdContractsResponses = {
    /**
     * Success
     */
    200: GetContractsResponse;
};

export type GetCrmMembersByIdContractsResponse = GetCrmMembersByIdContractsResponses[keyof GetCrmMembersByIdContractsResponses];

export type GetCrmMembersByIdPointsData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points';
};

export type GetCrmMembersByIdPointsErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdPointsError = GetCrmMembersByIdPointsErrors[keyof GetCrmMembersByIdPointsErrors];

export type GetCrmMembersByIdPointsResponses = {
    /**
     * Success
     */
    200: GetPointsResponse;
};

export type GetCrmMembersByIdPointsResponse = GetCrmMembersByIdPointsResponses[keyof GetCrmMembersByIdPointsResponses];

export type PostCrmMembersByIdPointsData = {
    /**
     * ポイント操作パラメータ
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points';
};

export type PostCrmMembersByIdPointsErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembersByIdPointsError = PostCrmMembersByIdPointsErrors[keyof PostCrmMembersByIdPointsErrors];

export type PostCrmMembersByIdPointsResponses = {
    /**
     * Success
     */
    200: GetPointsResponse;
};

export type PostCrmMembersByIdPointsResponse = PostCrmMembersByIdPointsResponses[keyof PostCrmMembersByIdPointsResponses];

export type PostCrmMembersByIdPointsAdjustData = {
    body: PointAdjustmentRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/points/adjust';
};

export type PostCrmMembersByIdPointsAdjustErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembersByIdPointsAdjustError = PostCrmMembersByIdPointsAdjustErrors[keyof PostCrmMembersByIdPointsAdjustErrors];

export type PostCrmMembersByIdPointsAdjustResponses = {
    /**
     * Success
     */
    200: PointAdjustmentResponse;
};

export type PostCrmMembersByIdPointsAdjustResponse = PostCrmMembersByIdPointsAdjustResponses[keyof PostCrmMembersByIdPointsAdjustResponses];

export type PostCrmMembersByIdMemosData = {
    body: CreateMemoRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos';
};

export type PostCrmMembersByIdMemosErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembersByIdMemosError = PostCrmMembersByIdMemosErrors[keyof PostCrmMembersByIdMemosErrors];

export type PostCrmMembersByIdMemosResponses = {
    /**
     * Success
     */
    200: CreateMemoResponse;
};

export type PostCrmMembersByIdMemosResponse = PostCrmMembersByIdMemosResponses[keyof PostCrmMembersByIdMemosResponses];

export type PostCrmMembersExportData = {
    body: ExportMembersRequest;
    path?: never;
    query?: never;
    url: '/crm/members/export';
};

export type PostCrmMembersExportErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembersExportError = PostCrmMembersExportErrors[keyof PostCrmMembersExportErrors];

export type PostCrmMembersExportResponses = {
    /**
     * Success
     */
    200: ExportMembersResponse;
};

export type PostCrmMembersExportResponse = PostCrmMembersExportResponses[keyof PostCrmMembersExportResponses];

export type GetCrmMembersByIdChangeHistoryData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/change-history';
};

export type GetCrmMembersByIdChangeHistoryErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdChangeHistoryError = GetCrmMembersByIdChangeHistoryErrors[keyof GetCrmMembersByIdChangeHistoryErrors];

export type GetCrmMembersByIdChangeHistoryResponses = {
    /**
     * Success
     */
    200: GetChangeHistoryResponse;
};

export type GetCrmMembersByIdChangeHistoryResponse = GetCrmMembersByIdChangeHistoryResponses[keyof GetCrmMembersByIdChangeHistoryResponses];

export type GetCrmMembersByIdCommunicationsData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/communications';
};

export type GetCrmMembersByIdCommunicationsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdCommunicationsError = GetCrmMembersByIdCommunicationsErrors[keyof GetCrmMembersByIdCommunicationsErrors];

export type GetCrmMembersByIdCommunicationsResponses = {
    /**
     * Success
     */
    200: GetCommunicationsResponse;
};

export type GetCrmMembersByIdCommunicationsResponse = GetCrmMembersByIdCommunicationsResponses[keyof GetCrmMembersByIdCommunicationsResponses];

export type PutCrmMembersByIdHealthInfoData = {
    body: UpdateHealthInfoRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/health-info';
};

export type PutCrmMembersByIdHealthInfoErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdHealthInfoError = PutCrmMembersByIdHealthInfoErrors[keyof PutCrmMembersByIdHealthInfoErrors];

export type PutCrmMembersByIdHealthInfoResponses = {
    /**
     * Success
     */
    200: PutHealthInfoResponse;
};

export type PutCrmMembersByIdHealthInfoResponse = PutCrmMembersByIdHealthInfoResponses[keyof PutCrmMembersByIdHealthInfoResponses];

export type PutCrmMembersByIdMarketingConsentData = {
    body: UpdateMarketingConsentRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/marketing-consent';
};

export type PutCrmMembersByIdMarketingConsentErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdMarketingConsentError = PutCrmMembersByIdMarketingConsentErrors[keyof PutCrmMembersByIdMarketingConsentErrors];

export type PutCrmMembersByIdMarketingConsentResponses = {
    /**
     * Success
     */
    200: PutMarketingConsentResponse;
};

export type PutCrmMembersByIdMarketingConsentResponse = PutCrmMembersByIdMarketingConsentResponses[keyof PutCrmMembersByIdMarketingConsentResponses];

export type DeleteCrmMembersByIdMemosByMemoIdData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
        /**
         * メモID
         */
        memoId: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos/{memoId}';
};

export type DeleteCrmMembersByIdMemosByMemoIdErrors = {
    /**
     * Memo not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type DeleteCrmMembersByIdMemosByMemoIdError = DeleteCrmMembersByIdMemosByMemoIdErrors[keyof DeleteCrmMembersByIdMemosByMemoIdErrors];

export type DeleteCrmMembersByIdMemosByMemoIdResponses = {
    /**
     * Success
     */
    200: {
        success?: boolean;
    };
};

export type DeleteCrmMembersByIdMemosByMemoIdResponse = DeleteCrmMembersByIdMemosByMemoIdResponses[keyof DeleteCrmMembersByIdMemosByMemoIdResponses];

export type PutCrmMembersByIdMemosByMemoIdData = {
    body: UpdateMemoRequest;
    path: {
        /**
         * 会員ID
         */
        id: string;
        /**
         * メモID
         */
        memoId: string;
    };
    query?: never;
    url: '/crm/members/{id}/memos/{memoId}';
};

export type PutCrmMembersByIdMemosByMemoIdErrors = {
    /**
     * Memo not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmMembersByIdMemosByMemoIdError = PutCrmMembersByIdMemosByMemoIdErrors[keyof PutCrmMembersByIdMemosByMemoIdErrors];

export type PutCrmMembersByIdMemosByMemoIdResponses = {
    /**
     * Success
     */
    200: UpdateMemoResponse;
};

export type PutCrmMembersByIdMemosByMemoIdResponse = PutCrmMembersByIdMemosByMemoIdResponses[keyof PutCrmMembersByIdMemosByMemoIdResponses];

export type GetCrmMembersByIdRelationshipsData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/relationships';
};

export type GetCrmMembersByIdRelationshipsErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdRelationshipsError = GetCrmMembersByIdRelationshipsErrors[keyof GetCrmMembersByIdRelationshipsErrors];

export type GetCrmMembersByIdRelationshipsResponses = {
    /**
     * Success
     */
    200: GetRelationshipsResponse;
};

export type GetCrmMembersByIdRelationshipsResponse = GetCrmMembersByIdRelationshipsResponses[keyof GetCrmMembersByIdRelationshipsResponses];

export type GetCrmMembersByIdServiceUsageData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/service-usage';
};

export type GetCrmMembersByIdServiceUsageErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdServiceUsageError = GetCrmMembersByIdServiceUsageErrors[keyof GetCrmMembersByIdServiceUsageErrors];

export type GetCrmMembersByIdServiceUsageResponses = {
    /**
     * Success
     */
    200: GetServiceUsageResponse;
};

export type GetCrmMembersByIdServiceUsageResponse = GetCrmMembersByIdServiceUsageResponses[keyof GetCrmMembersByIdServiceUsageResponses];

export type GetCrmMembersByIdTrainingRecordsData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/training-records';
};

export type GetCrmMembersByIdTrainingRecordsErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdTrainingRecordsError = GetCrmMembersByIdTrainingRecordsErrors[keyof GetCrmMembersByIdTrainingRecordsErrors];

export type GetCrmMembersByIdTrainingRecordsResponses = {
    /**
     * Success
     */
    200: GetTrainingRecordsResponse;
};

export type GetCrmMembersByIdTrainingRecordsResponse = GetCrmMembersByIdTrainingRecordsResponses[keyof GetCrmMembersByIdTrainingRecordsResponses];

export type GetCrmMembersByIdUsageHistoryData = {
    body?: never;
    path: {
        /**
         * 会員ID
         */
        id: string;
    };
    query?: never;
    url: '/crm/members/{id}/usage-history';
};

export type GetCrmMembersByIdUsageHistoryErrors = {
    /**
     * Member not found
     */
    404: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembersByIdUsageHistoryError = GetCrmMembersByIdUsageHistoryErrors[keyof GetCrmMembersByIdUsageHistoryErrors];

export type GetCrmMembersByIdUsageHistoryResponses = {
    /**
     * Success
     */
    200: GetUsageHistoryResponse;
};

export type GetCrmMembersByIdUsageHistoryResponse = GetCrmMembersByIdUsageHistoryResponses[keyof GetCrmMembersByIdUsageHistoryResponses];

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetOpenapiJsonError = GetOpenapiJsonErrors[keyof GetOpenapiJsonErrors];

export type GetOpenapiJsonResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenapiJsonResponse = GetOpenapiJsonResponses[keyof GetOpenapiJsonResponses];

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Internal server error
     */
    500: Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Success
     */
    200: RegisterResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetCrmAutoApprovalDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/crm/auto-approval/dashboard';
};

export type GetCrmAutoApprovalDashboardErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmAutoApprovalDashboardError = GetCrmAutoApprovalDashboardErrors[keyof GetCrmAutoApprovalDashboardErrors];

export type GetCrmAutoApprovalDashboardResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmAutoApprovalDashboardResponse = GetCrmAutoApprovalDashboardResponses[keyof GetCrmAutoApprovalDashboardResponses];

export type GetCrmAutoApprovalSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/crm/auto-approval/settings';
};

export type GetCrmAutoApprovalSettingsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmAutoApprovalSettingsError = GetCrmAutoApprovalSettingsErrors[keyof GetCrmAutoApprovalSettingsErrors];

export type GetCrmAutoApprovalSettingsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmAutoApprovalSettingsResponse = GetCrmAutoApprovalSettingsResponses[keyof GetCrmAutoApprovalSettingsResponses];

export type PutCrmAutoApprovalSettingsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/crm/auto-approval/settings';
};

export type PutCrmAutoApprovalSettingsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PutCrmAutoApprovalSettingsError = PutCrmAutoApprovalSettingsErrors[keyof PutCrmAutoApprovalSettingsErrors];

export type PutCrmAutoApprovalSettingsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutCrmAutoApprovalSettingsResponse = PutCrmAutoApprovalSettingsResponses[keyof PutCrmAutoApprovalSettingsResponses];

export type PostCrmMembershipApplicationsByIdApproveData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/membership-applications/{id}/approve';
};

export type PostCrmMembershipApplicationsByIdApproveErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembershipApplicationsByIdApproveError = PostCrmMembershipApplicationsByIdApproveErrors[keyof PostCrmMembershipApplicationsByIdApproveErrors];

export type PostCrmMembershipApplicationsByIdApproveResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembershipApplicationsByIdApproveResponse = PostCrmMembershipApplicationsByIdApproveResponses[keyof PostCrmMembershipApplicationsByIdApproveResponses];

export type PostCrmMembershipApplicationsByIdCancelData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/membership-applications/{id}/cancel';
};

export type PostCrmMembershipApplicationsByIdCancelErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembershipApplicationsByIdCancelError = PostCrmMembershipApplicationsByIdCancelErrors[keyof PostCrmMembershipApplicationsByIdCancelErrors];

export type PostCrmMembershipApplicationsByIdCancelResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembershipApplicationsByIdCancelResponse = PostCrmMembershipApplicationsByIdCancelResponses[keyof PostCrmMembershipApplicationsByIdCancelResponses];

export type PostCrmMembershipApplicationsByIdRejectData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/membership-applications/{id}/reject';
};

export type PostCrmMembershipApplicationsByIdRejectErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembershipApplicationsByIdRejectError = PostCrmMembershipApplicationsByIdRejectErrors[keyof PostCrmMembershipApplicationsByIdRejectErrors];

export type PostCrmMembershipApplicationsByIdRejectResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembershipApplicationsByIdRejectResponse = PostCrmMembershipApplicationsByIdRejectResponses[keyof PostCrmMembershipApplicationsByIdRejectResponses];

export type GetCrmMembershipApplicationsByIdData = {
    body?: never;
    path: {
        /**
         * id parameter
         */
        id: string;
    };
    query?: never;
    url: '/crm/membership-applications/{id}';
};

export type GetCrmMembershipApplicationsByIdErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembershipApplicationsByIdError = GetCrmMembershipApplicationsByIdErrors[keyof GetCrmMembershipApplicationsByIdErrors];

export type GetCrmMembershipApplicationsByIdResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembershipApplicationsByIdResponse = GetCrmMembershipApplicationsByIdResponses[keyof GetCrmMembershipApplicationsByIdResponses];

export type PostCrmMembershipApplicationsBulkApproveData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/crm/membership-applications/bulk-approve';
};

export type PostCrmMembershipApplicationsBulkApproveErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembershipApplicationsBulkApproveError = PostCrmMembershipApplicationsBulkApproveErrors[keyof PostCrmMembershipApplicationsBulkApproveErrors];

export type PostCrmMembershipApplicationsBulkApproveResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembershipApplicationsBulkApproveResponse = PostCrmMembershipApplicationsBulkApproveResponses[keyof PostCrmMembershipApplicationsBulkApproveResponses];

export type GetCrmMembershipApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/crm/membership-applications';
};

export type GetCrmMembershipApplicationsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembershipApplicationsError = GetCrmMembershipApplicationsErrors[keyof GetCrmMembershipApplicationsErrors];

export type GetCrmMembershipApplicationsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembershipApplicationsResponse = GetCrmMembershipApplicationsResponses[keyof GetCrmMembershipApplicationsResponses];

export type PostCrmMembershipApplicationsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/crm/membership-applications';
};

export type PostCrmMembershipApplicationsErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type PostCrmMembershipApplicationsError = PostCrmMembershipApplicationsErrors[keyof PostCrmMembershipApplicationsErrors];

export type PostCrmMembershipApplicationsResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCrmMembershipApplicationsResponse = PostCrmMembershipApplicationsResponses[keyof PostCrmMembershipApplicationsResponses];

export type GetCrmMembershipApplicationsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/crm/membership-applications/summary';
};

export type GetCrmMembershipApplicationsSummaryErrors = {
    /**
     * Internal server error
     */
    500: Error;
};

export type GetCrmMembershipApplicationsSummaryError = GetCrmMembershipApplicationsSummaryErrors[keyof GetCrmMembershipApplicationsSummaryErrors];

export type GetCrmMembershipApplicationsSummaryResponses = {
    /**
     * Success
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCrmMembershipApplicationsSummaryResponse = GetCrmMembershipApplicationsSummaryResponses[keyof GetCrmMembershipApplicationsSummaryResponses];
