// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/crm` | (string & {});
};

export type PaginatedMembersResponse = {
  data?: Array<MemberListItem>;
  pagination?: PaginationInfo;
};

export type PaginationInfo = {
  currentPage?: number;
  totalPages?: number;
  totalItems?: number;
  itemsPerPage?: number;
};

export type MemberListItem = {
  id?: string;
  memberNo?: string;
  name?: string;
  memberType?: string;
  status?: string;
  storeName?: string;
  brandId?: string;
  mainPlan?: string;
  joinDate?: string;
  lastVisitDate?: string;
  hasUnpaid?: boolean;
};

export type MemberDetailHeader = {
  id?: string;
  memberNo?: string;
  name?: string;
  nameKana?: string;
  status?: string;
  brandId?: string;
  storeName?: string;
  alerts?: Array<string>;
};

export type MemberBasicInfo = {
  id?: string;
};

export type UpdateBasicInfoRequest = {
  name: string;
  nameKana: string;
  zipCode: string;
  prefecture: string;
  city: string;
  addressLine: string;
  buildingName?: string;
  phone: string;
  email: string;
  emergencyContactName?: string;
  emergencyContactRelation?: string;
  emergencyContactPhone?: string;
};

export type GetMembersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: 50 | 100 | 200;
    /**
     * Member number, name, phone number, email, etc.
     */
    keyword?: string;
    storeId?: string;
    memberType?: string;
    status?: string;
    lastVisitDate?: string;
    /**
     * Sort fields. Example: name:asc,createdAt:desc
     */
    sort?: string;
  };
  url: '/members';
};

export type GetMembersResponses = {
  /**
   * Member list and pagination info
   */
  200: PaginatedMembersResponse;
};

export type GetMembersResponse = GetMembersResponses[keyof GetMembersResponses];

export type SearchMembersData = {
  body?: never;
  path?: never;
  query: {
    q: string;
  };
  url: '/members/search';
};

export type SearchMembersResponses = {
  /**
   * Search result list
   */
  200: Array<MemberListItem>;
};

export type SearchMembersResponse = SearchMembersResponses[keyof SearchMembersResponses];

export type ExportMembersData = {
  body: {
    format?: 'csv' | 'excel';
    target?: 'selected' | 'filtered_all';
    memberIds?: Array<string>;
    fields?: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/members/export';
};

export type ExportMembersResponses = {
  /**
   * Export job accepted, or file download URL
   */
  200: unknown;
};

export type GetMemberByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}';
};

export type GetMemberByIdResponses = {
  /**
   * Member summary (alerts, badges, status, etc.)
   */
  200: MemberDetailHeader;
};

export type GetMemberByIdResponse = GetMemberByIdResponses[keyof GetMemberByIdResponses];

export type GetMemberBasicInfoData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/basic-info';
};

export type GetMemberBasicInfoResponses = {
  /**
   * Success
   */
  200: MemberBasicInfo;
};

export type GetMemberBasicInfoResponse =
  GetMemberBasicInfoResponses[keyof GetMemberBasicInfoResponses];

export type UpdateMemberBasicInfoData = {
  body: UpdateBasicInfoRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/basic-info';
};

export type UpdateMemberBasicInfoResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type UpdateMemberHealthInfoData = {
  body: {
    healthDeclaration?: string;
    medicalHistory?: string;
    allergies?: string;
    exerciseRestrictions?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/health-info';
};

export type UpdateMemberHealthInfoResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type UpdateMemberMarketingConsentData = {
  body: {
    emailConsent?: boolean;
    smsConsent?: boolean;
    pushConsent?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/marketing-consent';
};

export type UpdateMemberMarketingConsentResponses = {
  /**
   * Updated
   */
  200: unknown;
};

export type GetMemberContractsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/contracts';
};

export type GetMemberContractsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberPointsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/points';
};

export type GetMemberPointsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberUsageHistoryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/usage-history';
};

export type GetMemberUsageHistoryResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberTrainingRecordsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/training-records';
};

export type GetMemberTrainingRecordsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberServiceUsageData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/service-usage';
};

export type GetMemberServiceUsageResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberCommunicationsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/communications';
};

export type GetMemberCommunicationsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberChangeHistoryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/change-history';
};

export type GetMemberChangeHistoryResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberRelationshipsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/relationships';
};

export type GetMemberRelationshipsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type GetMemberAuditLogsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/audit-logs';
};

export type GetMemberAuditLogsResponses = {
  /**
   * Success
   */
  200: unknown;
};

export type AdjustMemberPointsData = {
  body: {
    type: 'add' | 'subtract';
    points: number;
    reason: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/points/adjust';
};

export type AdjustMemberPointsResponses = {
  /**
   * Point adjustment result
   */
  200: unknown;
};

export type CreateMemberMemoData = {
  body: {
    memoType: 'warning' | 'vip' | 'other';
    content: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/members/{id}/memos';
};

export type CreateMemberMemoResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type DeleteMemberMemoData = {
  body?: never;
  path: {
    id: string;
    memo_id: string;
  };
  query?: never;
  url: '/members/{id}/memos/{memo_id}';
};

export type DeleteMemberMemoResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteMemberMemoResponse = DeleteMemberMemoResponses[keyof DeleteMemberMemoResponses];

export type UpdateMemberMemoData = {
  body: {
    memoType: 'warning' | 'vip' | 'other';
    content: string;
  };
  path: {
    id: string;
    memo_id: string;
  };
  query?: never;
  url: '/members/{id}/memos/{memo_id}';
};

export type UpdateMemberMemoResponses = {
  /**
   * Updated
   */
  200: unknown;
};
