// Auto-generated routes configuration
// Do not edit this file manually

export const routes = {
  '/': {
    router: '/',
    filePath: '(private)/(dashboard)',
    pattern: '/',
    private: true,
  },
  '/members/[id]': {
    router: (id: string | number) => `/members/${id}`,
    filePath: '(private)/members/[id]',
    pattern: '/members/:id',
    private: true,
  },
  '/membership-applications': {
    router: '/membership-applications',
    filePath: '(private)/membership-applications',
    pattern: '/membership-applications',
    private: true,
  },
  '/403': {
    router: '/403',
    filePath: '(public)/403',
    pattern: '/403',
    private: false,
  },
  '/login': {
    router: '/login',
    filePath: '(public)/login',
    pattern: '/login',
    private: false,
  },
} as const;

// List of all route keys
export const routeKeys = [
  '/',
  '/members/[id]',
  '/membership-applications',
  '/403',
  '/login',
] as const;

// List of all route patterns
export const routePatterns = [
  '/',
  '/members/:id',
  '/membership-applications',
  '/403',
  '/login',
] as const;
