// This file is auto-generated by @hey-api/openapi-ts
import {
  type DefaultError,
  type InfiniteData,
  type UseMutationOptions,
  infiniteQueryOptions,
  queryOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import { MemberDetails, Members, Memos, type Options, Points } from '../sdk.gen';
import type {
  AdjustMemberPointsData,
  CreateMemberMemoData,
  DeleteMemberMemoData,
  DeleteMemberMemoResponse,
  ExportMembersData,
  GetMemberAuditLogsData,
  GetMemberBasicInfoData,
  GetMemberBasicInfoResponse,
  GetMemberByIdData,
  GetMemberByIdResponse,
  GetMemberChangeHistoryData,
  GetMemberCommunicationsData,
  GetMemberContractsData,
  GetMemberPointsData,
  GetMemberRelationshipsData,
  GetMemberServiceUsageData,
  GetMemberTrainingRecordsData,
  GetMemberUsageHistoryData,
  GetMembersData,
  GetMembersResponse,
  SearchMembersData,
  SearchMembersResponse,
  UpdateMemberBasicInfoData,
  UpdateMemberHealthInfoData,
  UpdateMemberMarketingConsentData,
  UpdateMemberMemoData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getMembersQueryKey = (options?: Options<GetMembersData>) =>
  createQueryKey('getMembers', options);

/**
 * Get members list (pagination, filtering, sorting)
 */
export const getMembersOptions = (options?: Options<GetMembersData>) =>
  queryOptions<
    GetMembersResponse,
    DefaultError,
    GetMembersResponse,
    ReturnType<typeof getMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Members.getMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMembersQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getMembersInfiniteQueryKey = (
  options?: Options<GetMembersData>,
): QueryKey<Options<GetMembersData>> => createQueryKey('getMembers', options, true);

/**
 * Get members list (pagination, filtering, sorting)
 */
export const getMembersInfiniteOptions = (options?: Options<GetMembersData>) =>
  infiniteQueryOptions<
    GetMembersResponse,
    DefaultError,
    InfiniteData<GetMembersResponse>,
    QueryKey<Options<GetMembersData>>,
    number | Pick<QueryKey<Options<GetMembersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMembersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await Members.getMembers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMembersInfiniteQueryKey(options),
    },
  );

export const searchMembersQueryKey = (options: Options<SearchMembersData>) =>
  createQueryKey('searchMembers', options);

/**
 * Member search (for quick search using keyword or QR scanning)
 */
export const searchMembersOptions = (options: Options<SearchMembersData>) =>
  queryOptions<
    SearchMembersResponse,
    DefaultError,
    SearchMembersResponse,
    ReturnType<typeof searchMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await Members.searchMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchMembersQueryKey(options),
  });

/**
 * Execute export
 */
export const exportMembersMutation = (
  options?: Partial<Options<ExportMembersData>>,
): UseMutationOptions<unknown, DefaultError, Options<ExportMembersData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ExportMembersData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await Members.exportMembers({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMemberByIdQueryKey = (options: Options<GetMemberByIdData>) =>
  createQueryKey('getMemberById', options);

/**
 * Get member details (Header common info)
 */
export const getMemberByIdOptions = (options: Options<GetMemberByIdData>) =>
  queryOptions<
    GetMemberByIdResponse,
    DefaultError,
    GetMemberByIdResponse,
    ReturnType<typeof getMemberByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberByIdQueryKey(options),
  });

export const getMemberBasicInfoQueryKey = (options: Options<GetMemberBasicInfoData>) =>
  createQueryKey('getMemberBasicInfo', options);

/**
 * Get Basic Info tab data
 */
export const getMemberBasicInfoOptions = (options: Options<GetMemberBasicInfoData>) =>
  queryOptions<
    GetMemberBasicInfoResponse,
    DefaultError,
    GetMemberBasicInfoResponse,
    ReturnType<typeof getMemberBasicInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberBasicInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberBasicInfoQueryKey(options),
  });

/**
 * Update Basic Info
 */
export const updateMemberBasicInfoMutation = (
  options?: Partial<Options<UpdateMemberBasicInfoData>>,
): UseMutationOptions<unknown, DefaultError, Options<UpdateMemberBasicInfoData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateMemberBasicInfoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await MemberDetails.updateMemberBasicInfo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Health Info
 */
export const updateMemberHealthInfoMutation = (
  options?: Partial<Options<UpdateMemberHealthInfoData>>,
): UseMutationOptions<unknown, DefaultError, Options<UpdateMemberHealthInfoData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateMemberHealthInfoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await MemberDetails.updateMemberHealthInfo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Marketing Consent
 */
export const updateMemberMarketingConsentMutation = (
  options?: Partial<Options<UpdateMemberMarketingConsentData>>,
): UseMutationOptions<unknown, DefaultError, Options<UpdateMemberMarketingConsentData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateMemberMarketingConsentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await MemberDetails.updateMemberMarketingConsent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMemberContractsQueryKey = (options: Options<GetMemberContractsData>) =>
  createQueryKey('getMemberContracts', options);

/**
 * Get Contracts tab data
 */
export const getMemberContractsOptions = (options: Options<GetMemberContractsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberContractsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberContracts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberContractsQueryKey(options),
  });

export const getMemberPointsQueryKey = (options: Options<GetMemberPointsData>) =>
  createQueryKey('getMemberPoints', options);

/**
 * Get Points tab data (by brand)
 */
export const getMemberPointsOptions = (options: Options<GetMemberPointsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberPointsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberPointsQueryKey(options),
  });

export const getMemberUsageHistoryQueryKey = (options: Options<GetMemberUsageHistoryData>) =>
  createQueryKey('getMemberUsageHistory', options);

/**
 * Get Usage History tab data
 */
export const getMemberUsageHistoryOptions = (options: Options<GetMemberUsageHistoryData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberUsageHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberUsageHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberUsageHistoryQueryKey(options),
  });

export const getMemberTrainingRecordsQueryKey = (options: Options<GetMemberTrainingRecordsData>) =>
  createQueryKey('getMemberTrainingRecords', options);

/**
 * Get Training Records tab data
 */
export const getMemberTrainingRecordsOptions = (options: Options<GetMemberTrainingRecordsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberTrainingRecordsQueryKey>>(
    {
      queryFn: async ({ queryKey, signal }) => {
        const { data } = await MemberDetails.getMemberTrainingRecords({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMemberTrainingRecordsQueryKey(options),
    },
  );

export const getMemberServiceUsageQueryKey = (options: Options<GetMemberServiceUsageData>) =>
  createQueryKey('getMemberServiceUsage', options);

/**
 * Get Service Usage tab data
 */
export const getMemberServiceUsageOptions = (options: Options<GetMemberServiceUsageData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberServiceUsageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberServiceUsage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberServiceUsageQueryKey(options),
  });

export const getMemberCommunicationsQueryKey = (options: Options<GetMemberCommunicationsData>) =>
  createQueryKey('getMemberCommunications', options);

/**
 * Get Communications tab data
 */
export const getMemberCommunicationsOptions = (options: Options<GetMemberCommunicationsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberCommunicationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberCommunications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberCommunicationsQueryKey(options),
  });

export const getMemberChangeHistoryQueryKey = (options: Options<GetMemberChangeHistoryData>) =>
  createQueryKey('getMemberChangeHistory', options);

/**
 * Get Change History tab data
 */
export const getMemberChangeHistoryOptions = (options: Options<GetMemberChangeHistoryData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberChangeHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberChangeHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberChangeHistoryQueryKey(options),
  });

export const getMemberRelationshipsQueryKey = (options: Options<GetMemberRelationshipsData>) =>
  createQueryKey('getMemberRelationships', options);

/**
 * Get Relationships tab data
 */
export const getMemberRelationshipsOptions = (options: Options<GetMemberRelationshipsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberRelationshipsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberRelationships({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberRelationshipsQueryKey(options),
  });

export const getMemberAuditLogsQueryKey = (options: Options<GetMemberAuditLogsData>) =>
  createQueryKey('getMemberAuditLogs', options);

/**
 * Get Audit Logs (Access logs, etc.)
 */
export const getMemberAuditLogsOptions = (options: Options<GetMemberAuditLogsData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getMemberAuditLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MemberDetails.getMemberAuditLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMemberAuditLogsQueryKey(options),
  });

/**
 * Adjust Points (Headquarter only)
 */
export const adjustMemberPointsMutation = (
  options?: Partial<Options<AdjustMemberPointsData>>,
): UseMutationOptions<unknown, DefaultError, Options<AdjustMemberPointsData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<AdjustMemberPointsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Points.adjustMemberPoints({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add Memo
 */
export const createMemberMemoMutation = (
  options?: Partial<Options<CreateMemberMemoData>>,
): UseMutationOptions<unknown, DefaultError, Options<CreateMemberMemoData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<CreateMemberMemoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Memos.createMemberMemo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Memo
 */
export const deleteMemberMemoMutation = (
  options?: Partial<Options<DeleteMemberMemoData>>,
): UseMutationOptions<DeleteMemberMemoResponse, DefaultError, Options<DeleteMemberMemoData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteMemberMemoResponse,
    DefaultError,
    Options<DeleteMemberMemoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Memos.deleteMemberMemo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Memo
 */
export const updateMemberMemoMutation = (
  options?: Partial<Options<UpdateMemberMemoData>>,
): UseMutationOptions<unknown, DefaultError, Options<UpdateMemberMemoData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<UpdateMemberMemoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await Memos.updateMemberMemo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
